spring.application.name=backend-spring

server.port=443
server.ssl.key-store=/home/bingo/keystore.p12
server.ssl.key-store-password=ecolink123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

spring.datasource.url=jdbc:mysql://localhost:3306/bingo?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=bingo1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect